In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import sqlite3
import torchvision
import torch
import torch.nn as nn

from src.splitting import MonteCarloCV, KfoldCV
from src.dataset import Mitosis_Training_Dataset, Mitosis_Validation_Dataset


In [3]:
n = 10
samples = np.arange(n)

In [4]:
val_size = 0.2
test_size = 0.2
n_repeats = 5
seed = 42

mccv = MonteCarloCV(val_size, test_size, n_repeats)

for train, val, test in mccv.split(samples):
    print(train, val, test)

[0 3 4 5 8 9] [1 7] [2 6]
[1 3 5 6 7 8] [2 4] [0 9]
[0 1 2 4 6 8] [3 9] [5 7]
[0 1 2 4 6 9] [5 8] [3 7]
[0 1 4 6 7 9] [3 8] [2 5]


In [5]:
n_folds = 5
kcv = KfoldCV(n_folds, shuffle=False)

for train, val, test in kcv.split(samples):
    print(train, val, test)

[4 5 6 7 8 9] [0 1] [2 3]
[0 1 6 7 8 9] [2 3] [4 5]
[0 1 2 3 8 9] [4 5] [6 7]
[0 1 2 3 4 5] [6 7] [8 9]
[2 3 4 5 6 7] [8 9] [0 1]


In [8]:
from torchvision.models import densenet121

model = densenet121()
model